"""
Shared configuration constants for the AlphaGenome CIEMAT pipeline.
"""

# Plot colors
REF_COLOR = "#1f77b4"
ALT_COLOR = "#7a0019"
DELTA_COLOR = "#ff8c00"
DELTA_SECOND_COLOR = REF_COLOR

INSERTED_REGION_COLOR = "#9ecae1"
INSERTED_REGION_ALPHA = 0.18
INSERTED_REGION_LABEL = "HDR cassette (ALT)"

EXON_COLOR = "#1f77b4"
INTRON_COLOR = "#7a0019"
VARIANT_COLOR = "#D4A017"

# Plot labels
RNA_SEQ_LABEL = "RNA_SEQ"
SPLICE_SITES_LABEL = "SPLICE_SITES"
SPLICE_SITE_USAGE_LABEL = "SPLICE_SITE_USAGE"
SPLICE_JUNCTIONS_LABEL = "SPLICE_JUNCTIONS"

# Figure export
FIGURE_DPI = 300